### ISSUE TITLE
Unicode strings are not correctly handled by JUnit results parser

### ISSUE THREAD

**Issue by cegonse** [cegonse/cest#15]
A test case with an Unicode character in its name, such as:

```cpp
it("😀", []() { });
```

Will fail to compile as the JUnit report generation fails:
```
Traceback (most recent call last):
  File "framework/junit.py", line 94, in <module>
    xml = generate_junit_xml(test_suites)
  File "framework/junit.py", line 76, in generate_junit_xml
    time=test_case['time']
UnicodeEncodeError: 'ascii' codec can't encode character u'\U0001f600' in position 46: ordinal not in range(128)
```

**Comment by cegonse** [comment]
Closed by 621e3a7b9f917f7aed063311ceebc5a5807fd6ff
